//
// Created by renana on 5/25/23.
//

#ifndef MAGICAL_ITERATORS_SIDECROSSITERATOR_H
#define MAGICAL_ITERATORS_SIDECROSSITERATOR_H


class SideCrossIterator {

};


#endif //MAGICAL_ITERATORS_SIDECROSSITERATOR_H
